#!/bin/sh
set -eu
HERE="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
export PYWEBVIEW_GUI=qt
export QTWEBENGINE_DISABLE_SANDBOX=1
export QTWEBENGINE_CHROMIUM_FLAGS="${QTWEBENGINE_CHROMIUM_FLAGS:+$QTWEBENGINE_CHROMIUM_FLAGS }--no-sandbox --disable-gpu-sandbox"
cd "$HERE/usr/bin" || exit 1
exec "$HERE/usr/bin/conduit" "$@"
